# Site settings
title: azzurrio
header-img: img/home-bg.jpg
email: just.azzurri@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: ""
twitter_username: Azzurrio
github_username: Azzurrio
facebook_username: Azzurrio

# Build settings
markdown: kramdown
highlighter: pygments
excerpt_separator: ""
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
